# Generated by Django 4.2 on 2024-03-26 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 3, 26)),
        ),
    ]
