# Generated by Django 4.2 on 2024-03-26 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0002_alter_pettycash_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 16, 21, 41, 342730, tzinfo=datetime.timezone.utc)),
        ),
    ]
