# Generated by Django 4.2 on 2024-03-26 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0003_alter_pettycash_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='voucher',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 26, 17, 0, 48, 262435, tzinfo=datetime.timezone.utc)),
        ),
    ]
