# Generated by Django 4.2 on 2024-03-27 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0004_pettycash_voucher_alter_pettycash_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='to_or_from',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 10, 3, 25, 180133, tzinfo=datetime.timezone.utc)),
        ),
    ]
