# Generated by Django 4.2 on 2024-03-27 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0006_vouchercodestore_alter_pettycash_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pettycash',
            old_name='voucher',
            new_name='voucher_code',
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 10, 46, 52, 701286, tzinfo=datetime.timezone.utc)),
        ),
    ]
