# Generated by Django 4.2 on 2024-03-27 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0008_openingbalance_alter_pettycash_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalance',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 12, 54, 48, 806597, tzinfo=datetime.timezone.utc)),
        ),
    ]
