# Generated by Django 4.2 on 2024-03-27 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0009_openingbalance_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openingbalance',
            old_name='year',
            new_name='date',
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='current_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 13, 58, 33, 729765, tzinfo=datetime.timezone.utc)),
        ),
    ]
