# Generated by Django 4.2 on 2024-03-27 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0010_rename_year_openingbalance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 14, 3, 2, 591872, tzinfo=datetime.timezone.utc)),
        ),
    ]
