# Generated by Django 4.2 on 2024-03-27 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0012_alter_openingbalance_opening_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openingbalance',
            old_name='date',
            new_name='opening_date',
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 14, 10, 59, 498376, tzinfo=datetime.timezone.utc)),
        ),
    ]
