# Generated by Django 4.2 on 2024-03-27 14:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0013_rename_date_openingbalance_opening_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbalance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 27, 14, 18, 25, 51613, tzinfo=datetime.timezone.utc)),
        ),
    ]
