# Generated by Django 4.2 on 2024-03-28 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0014_alter_openingbalance_id_alter_pettycash_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 5, 49, 11, 544440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SBIBankPettyCash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('voucher_code', models.CharField(blank=True, max_length=150, unique=True)),
                ('to_or_from', models.CharField(max_length=200)),
                ('created_date', models.DateField(default=datetime.datetime(2024, 3, 28, 5, 49, 11, 544440, tzinfo=datetime.timezone.utc))),
                ('cash_flow', models.CharField(choices=[('Cash In', 'Cash In'), ('Cash Out', 'Cash Out')], max_length=50)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=1200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pettycash_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='FederalBankPettyCash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('voucher_code', models.CharField(blank=True, max_length=150, unique=True)),
                ('to_or_from', models.CharField(max_length=200)),
                ('created_date', models.DateField(default=datetime.datetime(2024, 3, 28, 5, 49, 11, 544440, tzinfo=datetime.timezone.utc))),
                ('cash_flow', models.CharField(choices=[('Cash In', 'Cash In'), ('Cash Out', 'Cash Out')], max_length=50)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=1200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pettycash_app.category')),
            ],
        ),
    ]
