# Generated by Django 4.2 on 2024-03-29 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0016_federalbank_sbibank_remove_sbibankpettycash_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingbalance',
            name='current_show',
        ),
        migrations.AlterField(
            model_name='federalbank',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 29, 4, 39, 50, 270144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 29, 4, 39, 50, 270144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sbibank',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 29, 4, 39, 50, 270144, tzinfo=datetime.timezone.utc)),
        ),
    ]
