# Generated by Django 4.2 on 2024-04-04 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pettycash_app', '0017_remove_openingbalance_current_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federalbank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voucher_signature/'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voucher_signature/'),
        ),
        migrations.AddField(
            model_name='sbibank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='voucher_signature/'),
        ),
        migrations.AlterField(
            model_name='federalbank',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sbibank',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
